tergen.o: tergen.cpp ../include/ode/ode.h ../include/ode/config.h \
  ../include/ode/compatibility.h ../include/ode/common.h \
  ../include/ode/error.h ../include/ode/contact.h ../include/ode/memory.h \
  ../include/ode/odemath.h ../include/ode/matrix.h ../include/ode/timer.h \
  ../include/ode/rotation.h ../include/ode/mass.h ../include/ode/misc.h \
  ../include/ode/objects.h ../include/ode/odecpp.h \
  ../include/ode/collision_space.h ../include/ode/collision.h \
  ../include/ode/collision_trimesh.h ../include/ode/odecpp_collision.h \
  ../include/ode/export-dif.h ../include/drawstuff/drawstuff.h \
  ../include/drawstuff/version.h Terrain.h
Terrain.o: Terrain.cpp ../include/drawstuff/drawstuff.h \
  ../include/drawstuff/version.h Terrain.h ../include/ode/ode.h \
  ../include/ode/config.h ../include/ode/compatibility.h \
  ../include/ode/common.h ../include/ode/error.h ../include/ode/contact.h \
  ../include/ode/memory.h ../include/ode/odemath.h \
  ../include/ode/matrix.h ../include/ode/timer.h \
  ../include/ode/rotation.h ../include/ode/mass.h ../include/ode/misc.h \
  ../include/ode/objects.h ../include/ode/odecpp.h \
  ../include/ode/collision_space.h ../include/ode/collision.h \
  ../include/ode/collision_trimesh.h ../include/ode/odecpp_collision.h \
  ../include/ode/export-dif.h VectorOp.h
